# travis.yml for https://github.com/giesselmann/selectION

language: cpp
compiler: gcc
dist: trusty

before_script:
    - sudo apt-get -qq update
    - sudo apt-get install -y libboost-filesystem-dev libboost-program-options-dev libboost-system-dev
    
script: 
    - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && make
    - src/selection